# Copyright (C) 2013 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/valentewx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/htc/valentewx/proprietary/bin/ewtzmud:/system/bin/ewtzmud \
        vendor/htc/valentewx/proprietary/lib/libchromatix_s5k3h2yx_default_video.so:/system/lib/libchromatix_s5k3h2yx_default_video.so \
        vendor/htc/valentewx/proprietary/lib/libchromatix_s5k3h2yx_hdr.so:/system/lib/libchromatix_s5k3h2yx_hdr.so \
        vendor/htc/valentewx/proprietary/lib/libchromatix_s5k3h2yx_hfr.so:/system/lib/libchromatix_s5k3h2yx_hfr.so \
        vendor/htc/valentewx/proprietary/lib/libchromatix_s5k3h2yx_preview.so:/system/lib/libchromatix_s5k3h2yx_preview.so \
        vendor/htc/valentewx/proprietary/lib/libchromatix_s5k3h2yx_zsl.so:/system/lib/libchromatix_s5k3h2yx_zsl.so \
        vendor/htc/valentewx/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
        vendor/htc/valentewx/proprietary/lib/libmllite.so:system/lib/libmllite.so \
        vendor/htc/valentewx/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
        vendor/htc/valentewx/proprietary/lib/libmpl.so:system/lib/libmpl.so \
        vendor/htc/valentewx/proprietary/lib/libmpl_jni.so:system/lib/libmpl_jni.so \
        vendor/htc/valentewx/proprietary/bin/netmgrd:/system/bin/netmgrd \
        vendor/htc/valentewx/proprietary/bin/qmuxd:/system/bin/qmuxd \
        vendor/htc/valentewx/proprietary/lib/libdiag.so:/system/lib/libdiag.so \
        vendor/htc/valentewx/proprietary/lib/libdsi_netctrl.so:/system/lib/libdsi_netctrl.so \
        vendor/htc/valentewx/proprietary/lib/libdsutils.so:/system/lib/libdsutils.so \
        vendor/htc/valentewx/proprietary/lib/libidl.so:/system/lib/libidl.so \
        vendor/htc/valentewx/proprietary/lib/libqdi.so:/system/lib/libqdi.so \
        vendor/htc/valentewx/proprietary/lib/libqdp.so:/system/lib/libqdp.so \
        vendor/htc/valentewx/proprietary/lib/libqmi_cci.so:/system/lib/libqmi_cci.so \
        vendor/htc/valentewx/proprietary/lib/libqmi_common_so.so:/system/lib/libqmi_common_so.so \
        vendor/htc/valentewx/proprietary/lib/libqmi_csi.so:/system/lib/libqmi_csi.so \
        vendor/htc/valentewx/proprietary/lib/libqmi_encdec.so:/system/lib/libqmi_encdec.so \
        vendor/htc/valentewx/proprietary/lib/libqmiservices.so:/system/lib/libqmiservices.so \
        vendor/htc/valentewx/proprietary/lib/libqmi.so:/system/lib/libqmi.so \
        vendor/htc/valentewx/proprietary/lib/libnetmgr.so:/system/lib/libnetmgr.so \
        vendor/htc/valentewx/proprietary/lib/libril-qc-qmi-1.so:/system/lib/libril-qc-qmi-1.so \
        vendor/htc/valentewx/proprietary/lib/libril-qcril-hook-oem.so:/system/lib/libril-qcril-hook-oem.so \
	vendor/htc/valentewx/proprietary/lib/libBMLSupports.so:/system/lib/libBMLSupperts.so \
	vendor/htc/valentewx/proprietary/lib/libCdAbLayer.so:/system/lib/libCdAbLayer.so \
	vendor/htc/valentewx/proprietary/lib/libJellyPG.so:/system/lib/libJellyPG.so \
	vendor/htc/valentewx/proprietary/lib/libMTVMFCls.so:/system/lib/libMTVMFCls.so \
	vendor/htc/valentewx/proprietary/lib/libnm325.so:/system/lib/libnm325.so \
	vendor/htc/valentewx/proprietary/bin/jellyservice:/system/bin/jellyservice \
	vendor/htc/valentewx/proprietary/bin/mtvmfservice:/system/bin/mtvmfservice \
	vendor/htc/valentewx/proprietary/bin/mtvmfrecservice:/system/bin/mtvmfrecservice \
	vendor/htc/valentewx/proprietary/bin/felica_agent:/system/bin/felica_agent \
	vendor/htc/valentewx/proprietary/bin/felica_daemon:/system/bin/felica_daemon \
	vendor/htc/valentewx/proprietary/bin/felica_startup:/system/bin/felica_startup \
	vendor/htc/valentewx/proprietary/etc/felica/common.cfg:/system/etc/felica/common.cfg \
	vendor/htc/valentewx/proprietary/etc/felica/mfm.cfg:/system/etc/felica/mfm.cfg \
	vendor/htc/valentewx/proprietary/etc/felica/mfs.cfg:/system/etc/felica/mfs.cfg \
	vendor/htc/valentewx/proprietary/app/GMobileTV.apk:/system/app/GMobileTV.apk \
        vendor/htc/valentewx/proprietary/app/KDDI_Felicalock.apk:/system/app/KDDI_Felicalock.apk \
        vendor/htc/valentewx/proprietary/app/MobileFeliCaClient.apk:/system/app/MobileFeliCaClient.apk \
        vendor/htc/valentewx/proprietary/app/MobileFeliCaMenuApp.apk:/system/app/MobileFeliCaMenuApp.apk \
        vendor/htc/valentewx/proprietary/app/MobileFeliCaSettingApp.apk:/system/app/MobileFeliCaSettingApp.apk \
        vendor/htc/valentewx/proprietary/app/MobileFeliCaWebPluginBoot.apk:/system/app/MobileFeliCaWebPluginBoot.apk
